---
- name: Retrieve topic-id from component
  dci_component:
    id: '{{ dci_retrieve_component_component_id }}'
  register: _component

- name: Retrieve topic information from topic
  dci_topic:
    id: '{{ _component.component.topic_id }}'
    embed: product
  register: _topic

- name: Download the component when it's a Compose
  vars:
    component_name: '{% if dci_retrieve_component_component_name is defined -%}
    {{ dci_retrieve_component_component_name }}
    {%- else -%}
    {{ _topic.topic.name }}
    {%- endif %}'
  command: /bin/dci-downloader '{{ component_name }}'
    '{{ dci_retrieve_component_local_repo }}'
    --variant OpenStack --arch x86_64
    --component-id {{ dci_retrieve_component_component_id }}
  when:
    - _component.component.type.lower() == "compose"

- name: Download the component when it's not a Compose
  vars:
    component_name: '{% if dci_retrieve_component_component_name is defined -%}
    {{ dci_retrieve_component_component_name }}
    {%- else -%}
    {{ _topic.topic.name }}
    {%- endif %}'
  command: /bin/dci-downloader '{{ component_name }}'
    '{{ dci_retrieve_component_local_repo }}'
    --all
    --component-id {{ dci_retrieve_component_component_id }}
  when:
    - _component.component.type.lower() != "compose"
