---
- name: Retrieve topic-id from component
  dci_component:
    id: '{{ dci_retrieve_component_component_id }}'
  register: _component

- name: Retrieve topic information from topic
  dci_topic:
    id: '{{ _component.component.topic_id }}'
    embed: product
  register: _topic

- name: Configure local yum repository file
  yum_repository:
    name: '{{ _topic.topic.product.name }}'
    description: '{{ _component.component.name }}'
    baseurl: '{{ dci_retrieve_component_repo_url | default("https://repo.distributed-ci.io") }}/{{ _topic.topic.product_id }}/{{ _topic.topic.id }}/{{ _component.component.id }}/'
    sslclientcert: '{{ dci_retrieve_component_sslclientcert | default("/etc/ssl/repo/dci.crt") }}'
    sslclientkey: '{{ dci_retrieve_component_sslclientkey | default("/etc/ssl/repo/dci.key") }}'
    enabled: no
  become: True
  notify: "sync component"

- meta: flush_handlers
