---
- name: Retrieve topic-id from component
  dci_component:
    id: '{{ dci_retrieve_component_component_id }}'
  register: _component

- name: Retrieve topic information from topic
  dci_topic:
    id: '{{ _component.component.topic_id }}'
    embed: product
  register: _topic

- name: Configure local yum repository file
  yum_repository:
    name: '{{ _topic.topic.product.name }}'
    description: '{{ _component.component.name }}'
    baseurl: '{{ dci_retrieve_component_repo_url }}/{{ _topic.topic.product_id }}/{{ _topic.topic.id }}/{{ _component.component.id }}/'
    sslverify: '{{ dci_retrieve_component_sslverify }}'
    sslclientcert: '{{ dci_retrieve_component_sslclientcert }}'
    sslclientkey: '{{ dci_retrieve_component_sslclientkey }}'
    enabled: no
  become: True
  notify: "sync component"

- meta: flush_handlers
