---
- name: Check if a directory exist
  file:
    path: '{{ dci_retrieve_component_local_repo }}/{{ component_name }}'
    state: directory
  become: true

- name: Get repomd.xml
  uri:
    client_cert: '{{ dci_retrieve_component_sslclientcert }}'
    client_key: '{{ dci_retrieve_component_sslclientkey }}'
    return_content: true
    url: '{{ dci_retrieve_component_repo_url }}/{{ _topic.topic.product_id }}/{{ _topic.topic.id }}/{{ _component.component.id }}/repodata/repomd.xml'
    validate_certs: '{{ dci_retrieve_component_sslverify }}'
  register: repomd
  become: true

- name: Get Primary URL
  xml:
    xmlstring: '{{ repomd.content }}'
    xpath: /x:repomd/x:data[@type='primary']/x:location
    namespaces:
      x: http://linux.duke.edu/metadata/repo
    attribute: x:href
    content: attribute
  register: primary

- name: Download Primary
  get_url:
    client_cert: '{{ dci_retrieve_component_sslclientcert }}'
    client_key: '{{ dci_retrieve_component_sslclientkey }}'
    dest: /tmp/test.xml.gz
    url: "{{ dci_retrieve_component_repo_url }}/{{ _topic.topic.product_id }}/\
    {{ _topic.topic.id }}/{{ _component.component.id }}/{{ primary.matches[0].values()[0].href }}"
    validate_certs: '{{ dci_retrieve_component_sslverify }}'
    force: true
  become: true
  register: primary_file

- name: Decompress the Primary file  # noqa 503
  shell: gunzip -f -c /tmp/test.xml.gz > /tmp/test.xml
  become: true
  when: primary_file.changed

- name: Cleanup RPMs  # noqa 301
  command: "./cleanup_repo.py {{ dci_retrieve_component_local_repo }}/{{ component_name }}"
  args:
    chdir: "{{ role_path }}/files"
  become: true

- name: Detect package manager
  set_fact:
    yum_cmd: yum
    reposync_cmd: reposync
  when: (ansible_distribution == "CentOS" or ansible_distribution == "RedHat") and
        (ansible_distribution_major_version <= "7")

- name: Detect package manager
  set_fact:
    yum_cmd: dnf
    reposync_cmd: dnf reposync
  when: (ansible_distribution == "CentOS" or ansible_distribution == "RedHat") and
        (ansible_distribution_major_version >= "8")

- name: Cleanup local yum cache  # noqa 301
  command: "{{ yum_cmd }} --config=/etc/yum.repos.d/{{ component_name }}.repo clean metadata --disablerepo=* --enablerepo={{ component_name }}"
  args:
    warn: false
  become: true

- name: Syncing remote repository to local directory  # noqa 301
  command: "{{ reposync_cmd }} --config=/etc/yum.repos.d/{{ component_name }}.repo
  --arch={{ dci_retrieve_component_arch }}
  --repoid={{ component_name }}
  -l -m --download-meta -n -d
  -p {{ dci_retrieve_component_local_repo }}/"
  become: true

- name: Check if a group file exist
  stat:
    path: '{{ dci_retrieve_component_local_repo }}/{{ component_name }}/comps.xml'
  register: comps
  become: true

- name: Running createrepo locally  # noqa 301
  command: createrepo --update {% if comps.stat.exists %}-g comps.xml{% endif %} "{{ dci_retrieve_component_local_repo }}/{{ component_name }}"
  args:
    chdir: "{{ dci_retrieve_component_local_repo }}/"
  become: true
