---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint: |
  yamllint tasks
platforms:
  - name: el7
    image: centos:7
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
  - name: el8
    image: centos:8
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  log: true
  connection_options:
    ansible_user: centos
  env:
    ANSIBLE_LIBRARY: /var/tmp/dci/modules/
    ANSIBLE_MODULE_UTILS: /var/tmp/dci/module_utils/
  lint: |
    ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - destroy
verifier:
  name: testinfra
  lint: |
    flake8
