---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint:
  - yamllint
platforms:
  - name: el7
    image: centos:7
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  connection_options:
    ansible_user: centos
  env:
    ANSIBLE_LIBRARY: /var/tmp/dci/modules/
    ANSIBLE_MODULE_UTILS: /var/tmp/dci/module_utils/
  lint:
    - ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - destroy
verifier:
  name: testinfra
  lint:
    - flake8
